baseURL = 'https://skeletrox.github.io'
languageCode = 'en-us'
title = "Sriram's Website"
theme = 're-terminal'
pagination.PagerSize = 5
homeSubtitle = "Sriram's blog"

# Set disableReadOtherPosts to true in order to hide the links to other posts.
disableReadOtherPosts = false

# Enable sharing buttons, if you like
enableSharingButtons = true

# Show a global language switcher in the navigation bar
enableGlobalLanguageMenu = true

# Metadata mostly used in document's head
description = "Sriram's website"
keywords = "homepage, blog"
images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Sriram's Website"
    subtitle = "Sriram's Website"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

  [languages.en.params]
    subtitle  = "Sriram's portfolio Website"

    [languages.en.params.logo]
      logoText = "Sriram Venkatachalam Ramaswamy"
      logoHomeLink = "/"

  [languages.en.menu]
    [[languages.en.menu.main]]
      identifier = "portfolio"
      name       = "Portfolio"
      url        = "/portfolio"

    [[languages.en.menu.main]]
      identifier = "resume"
      name       = "Resume"
      url        = "/res/sriram_resume.pdf"

    [[languages.en.menu.main]]
      idenitifier = "personal_blog"
      name        = "Blog"
      url         = "/personal_blog"

    [[languages.en.menu.main]]
      identifier = "tech_blog"
      name       = "Tech"
      weight     = 10
    
    [[languages.en.menu.main]]
      parent     = "tech_blog"
      identifier = "general_tech"
      name       = "General Tech"
      url        = "/tech_blog"

    [[languages.en.menu.main]]
      identifier = "contact"
      name       = "Contact"
      url        = "/contact"

    [[languages.en.menu.main]]
      identifier = "distributed_systems"
      name       = "Distributed Systems"
      url        = "/distributed_systems"
      parent     = "tech_blog"

[params]

  contentTypeName = "about"
  showMenuItems = 5

  themeColor = "green"

  [[params.social]]
    name = "twitter"
    url = "https://x.com/SkeletroxVR"

  Toc = true
  TocTitle = true
