baseURL = 'https://skeletrox.github.io'
languageCode = 'en-us'
title = 'Portfolio - Sriram Venkatachalam Ramaswamy'
theme = 'hello-friend-ng'
pagination.PagerSize = 10
homeSubtitle = "A simple and beautiful blog"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = true

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Portfolio - Sriram Venkatachalam Ramaswamy"
    subtitle = "Sriram's Website"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

  [languages.en.params]
    subtitle  = "Sriram's portfolio Website"

    [languages.en.params.logo]
      logoText = "Sriram Venkatachalam Ramaswamy"
      logoHomeLink = "/portfolio"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "portfolio"
    name       = "Portfolio"
    url        = "/portfolio"
